/*
 * tuto de génération openapi
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.api;

import org.junit.Test;
import org.junit.Ignore;


import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;


/**
 * API tests for DefaultApi
 */
@Ignore
public class DefaultApiTest {

    private final DefaultApi api = new DefaultApi();

    /**
     * Create a pet
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void createPetsTest() throws Exception {
        api.createPets();

        // TODO: test validations
    }
    /**
     * Info for a specific pet
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void showPetByIdTest() throws Exception {
        String petId = null;
        api.showPetById(petId);

        // TODO: test validations
    }
}
