/*
 * tuto de génération openapi
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.api;

import org.junit.Test;
import org.junit.Ignore;


import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;


/**
 * API tests for PetsApi
 */
@Ignore
public class PetsApiTest {

    private final PetsApi api = new PetsApi();

    /**
     * List all pets
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void listPetsTest() throws Exception {
        Integer limit = null;
        api.listPets(limit);

        // TODO: test validations
    }
}
